.github/workflows/deploy-site.yml

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix deploy

---

src/app/layout/basic/basic.component.html
src/app/layout/layout.module.ts
src/app/routes/passport/loginV2/login.component.ts
src/environments/environment.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Nc zt 327 modificacion icono dashboard

---

src/app/layout/basic/basic.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: la sidebar va colapsada por defecto

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ML Change Readme

---

.github/workflows/deploy-site.yml

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ml update deploy library

---

.github/workflows/deploy-site.yml

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ml fix ftpdeploy version

---

.github/workflows/deploy-site.yml
src/app/routes/default/default.component.html
src/app/routes/passport/passport-routing.module.ts
src/environments/environment.qa.ts
src/environments/environment.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

test deploy

---

src/app/layout/layout.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: agrego todos los iconos de una sola vez al modulo LayoutModule

---

src/app/routes/widgets/pending-vacations/pending-vacations.component.ts
src/app/routes/widgets/widgets.module.ts
src/app/routes/zamba/rule/rule.component.html
src/app/routes/zamba/rule/rule.component.ts
src/app/shared/shared-zorro.module.ts
src/assets/tmp/i18n/es-ES.json
src/assets/tmp/i18n/es-Es.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

EA-RRHH-ZT349: added Error message in rule.component

---

src/app/app.module.ts
src/app/core/net/default.interceptor.ts
src/app/routes/passport/services/passport.service.ts
src/app/routes/widgets-container/widgets-container.component.ts
src/app/services/zamba/zamba.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: ZT-346 manejo del jwt

---

src/app/routes/pro/account/center/center.component.html
src/app/routes/pro/account/center/center.component.ts
src/app/routes/pro/account/center/entitie/employeeUser
src/app/routes/pro/account/center/entitie/employeeUser.ts
src/app/routes/pro/account/center/service/employee-user.service.spec.ts
src/app/routes/pro/account/center/service/employee-user.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Ea rrhh zt317 modificar menu perfil

---

src/app/layout/basic/basic.component.ts
src/app/services/message-listener.service.spec.ts
src/app/services/message-listener.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: servicio para escuchar mensajes de formularios de zamba

---

src/app/layout/basic/basic.component.ts
src/app/services/message-listener.service.spec.ts
src/app/services/message.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: ZT-416 Comunicacion a traves de mensajes desde el dashboar al iframe

---

src/app/app.component.ts
src/app/core/net/default.interceptor.ts
src/app/layout/basic/basic.component.html
src/app/routes/passport/login/login.component.ts
src/app/routes/passport/loginV2/login.component.html
src/app/routes/passport/loginV2/login.component.ts
src/app/routes/passport/register/register.component.html
src/app/routes/passport/resend-verification-email/resend-verificationemail.component.html
src/app/routes/passport/services/passport.service.ts
src/app/routes/pro/account/center/center.component.ts
src/app/routes/widgets-container/widgets-container.component.ts
src/app/routes/widgets/calendar/calendar.component.ts
src/app/routes/widgets/carousel/carousel.component.ts
src/app/routes/widgets/pending-tasks/pending-tasks.component.ts
src/app/routes/widgets/pending-vacations/pending-vacations.component.ts
src/app/routes/widgets/videoplayer/videoplayer.component.ts
src/app/routes/zamba/rule/rule.component.html
src/app/routes/zamba/rule/rule.component.ts
src/app/services/message.service.ts
src/app/services/zamba/zamba.service.ts
src/environments/environment.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Ml relogin token

---

src/app/layout/passport/passport.component.less
src/app/routes/passport/loginV2/login.component.html
src/app/routes/passport/loginV2/login.component.less

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: cambios en el login a pedido de gustavo

---

src/app/routes/widgets/pending-vacations/entitie/vacation.ts
src/app/routes/widgets/pending-vacations/pending-vacations.component.html
src/app/routes/widgets/pending-vacations/pending-vacations.component.less
src/app/routes/widgets/pending-vacations/pending-vacations.component.ts
src/app/routes/widgets/view-form/view-form.component.html
src/app/routes/widgets/view-form/view-form.component.less
src/app/routes/widgets/view-form/view-form.component.spec.ts
src/app/routes/widgets/view-form/view-form.component.ts
src/app/routes/zamba/zamba-routing.module.ts
src/app/routes/zamba/zamba.module.ts
src/assets/tmp/i18n/es-ES.json
src/assets/tmp/i18n/es-Es.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Ea rrhh zt ajustes widget vacaciones

---

src/app/routes/passport/loginV2/login.component.ts
src/environments/environment.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: usuario registrado pero no validado

---

src/app/routes/passport/loginV2/login.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: ZT-467 login con credenciales no validas

---

src/app/routes/widgets/pending-vacations/entitie/generic.ts
src/app/routes/widgets/pending-vacations/pending-vacations.component.ts
src/app/routes/widgets/pending-vacations/service/pending-vacations.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

EA-RRHH: cambio post por get para obtener vacaciones

---

src/app/routes/passport/loginV2/login.component.ts
src/app/routes/widgets/pending-tasks/pending-tasks.component.html
src/app/routes/widgets/pending-tasks/pending-tasks.component.ts
src/app/routes/zamba/rule/rule.component.ts
src/app/services/message.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: apertura de tareas pendientes

---

src/app/app.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: ZT-423 no reconocia el provider del TokenService

---

src/app/routes/widgets/pending-tasks/pending-tasks.component.css
src/app/routes/widgets/pending-tasks/pending-tasks.component.html
src/app/routes/widgets/pending-tasks/pending-tasks.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC-ZT-428-BotonRecargaTareasPendientes

---

src/app/routes/passport/register-result/register-result.component.html

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: han solicitado la accion de reenvio tambien en el register-result

---

src/app/layout/basic/basic.component.html
src/app/layout/basic/basic.component.ts
src/app/layout/basic/widgets/user.component.ts
src/app/routes/pro/account/center/center.component.html
src/app/routes/pro/account/center/center.component.ts
src/app/routes/pro/account/center/entitie/employeeUser.ts
src/app/services/zamba/zamba.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: ZT-482 avatar en center component y basic component

---

src/app/routes/dashboard/dashboard-routing.module.ts
src/app/routes/widgets/pending-vacations/pending-vacations.component.html
src/app/routes/widgets/pending-vacations/pending-vacations.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Ea rrhh zt530 ajustesde widget vacaciones

---

src/app/routes/dashboard/dashboard-routing.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

EA}-RRHH}-ZT397: Updated navigation route when i log in the app

---

src/app/layout/layout.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: fix LINT errors

---

src/app/routes/passport/register/register.component.html
src/app/routes/passport/resend-verification-email/resend-verificationemail.component.html

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC:reCaptcha key

---

src/app/app.module.ts
src/app/routes/dashboard/dashboard-routing.module.ts
src/app/routes/dashboard/dashboard.module.ts
src/app/routes/default/default.component.html
src/app/routes/default/default.component.ts
src/app/signature-container/signature-container.component.html
src/app/signature-container/signature-container.component.less
src/app/signature-container/signature-container.component.spec.ts
src/app/signature-container/signature-container.component.ts
src/app/signature/signature.component.html
src/app/signature/signature.component.less
src/app/signature/signature.component.spec.ts
src/app/signature/signature.component.ts
src/app/signature/signature.module.ts
src/app/signature/signature.service.ts
src/styles.less

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Nc zt 12 2 da parte firma electronica

---

src/app/signature/signature.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: se quita el onInit del componente para que lint deje hacer el deploy

---

src/app/signature/signature.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: se quita el implements onInit del signature component

---

src/app/qrgenerator-container/qr.service.ts
src/app/qrgenerator-container/qrgenerator-container.component.html
src/app/qrgenerator-container/qrgenerator-container.component.less
src/app/qrgenerator-container/qrgenerator-container.component.ts
src/app/qrgenerator-container/qrgenerator-container.module.ts
src/app/routes/dashboard/dashboard-routing.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Nc zt 627 qr generator

---

src/app/core/i18n/i18n.service.ts
src/assets/tmp/i18n/en-US.json
src/assets/tmp/i18n/en-US.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

EA-RRHH-ZT518: English language fixed

---

src/app/routes/welcome/initial-password-wizard/initial-password-wizard.component.html

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: FixRenderizacionDelComponenteDeResetPass

---

src/app/routes/passport/passport-routing.module.ts
src/assets/tmp/i18n/en-US.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: internacionalizacion de textos en nuevo password

---

src/app/routes/routes-routing.module.ts
src/app/routes/welcome/initial-password-wizard/initial-password-wizard.component.html
src/app/routes/widgets/view-form/view-form.component.html
src/app/routes/widgets/view-form/view-form.component.ts
src/app/signature-container-v2/signature-container-v2.component.ts
src/app/signature-v2/signature-v2.component.html
src/app/signature-v2/signature-v2.component.less
src/app/signature-v2/signature-v2.component.ts
src/app/signature/signature.module.ts
src/app/signature/signature.service.ts
src/environments/environment.local.ts
src/environments/environment.prod.ts
src/environments/environment.qa.ts
src/environments/environment.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Nc zt 713 guardar firma electronica en entidad zamba

---

src/app/signature-container-v2/signature-container-v2.component.ts
src/app/signature-v2/signature-v2.component.ts
src/assets/tmp/i18n/es-ES.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: recibe parametros enviados desde el formulario de zamba

---

src/app/routes/widgets/view-form/view-form.component.html
src/app/signature-container-v2/signature-container-v2.component.ts
src/app/signature-v2/signature-v2.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: paso por parametro el TaskID

---

src/app/routes/passport/loginV2/login.component.html
src/app/routes/passport/loginV2/login.component.ts
src/app/routes/passport/register/register.component.html
src/app/routes/passport/register/register.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

NC: add suffixTemplate into password inputs
